version: '3'

services:
  eventProject:
    image: ahmeddocer/devops-project
    ports:
      - "8080:8080"
    volumes:
      - ./target/eventProject.jar:/eventProject.jar
    command: ["java", "-jar", "/eventProject.jar"]

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: eventsproject
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  dbdata:
